services:
  api:
    container_name: "snippet-service-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: snippet-service-db
      DB_HOST: postgres_db_snippet_service
      DB_PORT: 5432

  db:
    container_name: postgres_db_snippet_service
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippet-service-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: